- !CategoricalParameter
  jaml_variable: JINA_MODEL_NAME
  choices:
    - resnet18
    - alexnet
    - squeezenet1_0
    - vgg16
    - densenet161
    - inception_v3
    - googlenet
    - shufflenet_v2_x1_0
    - mobilenet_v2
    - resnext50_32x4d
    - wide_resnet50_2
    - mnasnet1_0